# Generated by Django 3.0.7 on 2020-10-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Category',
            field=models.ManyToManyField(to='menu.Category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Courier',
            field=models.ManyToManyField(to='accounts.Courier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='WorkHour',
            field=models.ManyToManyField(to='accounts.WorkHour'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='workhour',
            unique_together={('owner', 'weekday')},
        ),
    ]
