# Generated by Django 3.0.7 on 2020-10-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_basketlist_time'),
        ('accounts', '0003_auto_20201018_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='current_order_number',
        ),
        migrations.AddField(
            model_name='courier',
            name='assign_order',
            field=models.ManyToManyField(null=True, to='order.BasketList'),
        ),
    ]
