# Generated by Django 3.0.7 on 2020-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_basketlist_time'),
        ('accounts', '0004_auto_20201020_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='assign_order',
            field=models.ManyToManyField(blank=True, to='order.BasketList'),
        ),
    ]
