# Generated by Django 3.0.7 on 2020-10-12 07:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('surname', models.CharField(max_length=56, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fb_id', models.CharField(blank=True, max_length=765, null=True)),
                ('adress', models.TextField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('owner', models.IntegerField()),
                ('client_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='order.Client')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('client_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='order.Client')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
            ],
        ),

    ]
