# Generated by Django 3.0.7 on 2020-10-15 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daily_id', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Waiting Incoming'), (2, 'Accepted (Outgoing)'), (3, 'Being_Delivered(Ready)'), (4, 'Completed')], default=1, verbose_name='status')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('being_delievered', models.DateTimeField(null=True)),
                ('received', models.DateTimeField(null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Client')),
                ('items', models.ManyToManyField(to='order.OrderItem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
