# Generated by Django 3.0.7 on 2020-10-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_basketlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketlist',
            name='daily_id',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
