# Generated by Django 3.0.7 on 2020-10-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201018_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketlist',
            name='comment',
        ),
    ]
