# Generated by Django 3.0.7 on 2020-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20201018_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketlist',
            name='time',
            field=models.IntegerField(default=25),
        ),
    ]
