# Generated by Django 3.0.7 on 2020-10-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20201020_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketlist',
            name='being_delievered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketlist',
            name='received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
